#!/bin/bash
#
# STERLING SIGNALS - FRIDAY PIPELINE ORCHESTRATOR
# ================================================
# Runs the complete weekly pipeline locally:
#   1. Scanner (Pure Technical Signal Detector — $0 cost)
#   2. Git commit and push
#
# LLM analysis (thematic + investment gate + DD) now runs via Claude.ai chat.
# Attach sterling_prompt_library.md to Claude.ai after reviewing signals.
# Live tweets generated by live_tweet.yml → live_tweet_generator.py.
#
# Usage:
#   ./run_friday.sh              # Full production run
#   ./run_friday.sh --test       # Test mode (no API calls where possible)
#   ./run_friday.sh --no-push    # Run without pushing to GitHub
#
# Prerequisites:
#   - Git configured with push access to repo
#

set -e  # Exit on error

# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Load .env file if it exists
if [ -f ".env" ]; then
    set -a
    source .env
    set +a
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default options
TEST_MODE=false
NO_PUSH=false

# ═══════════════════════════════════════════════════════════════════════════════
# ARGUMENT PARSING
# ═══════════════════════════════════════════════════════════════════════════════

while [[ $# -gt 0 ]]; do
    case $1 in
        --test)
            TEST_MODE=true
            shift
            ;;
        --no-push)
            NO_PUSH=true
            shift
            ;;
        -h|--help)
            echo "Usage: ./run_friday.sh [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --test             Run in test mode (minimal API calls)"
            echo "  --no-push          Don't push to GitHub"
            echo "  -h, --help         Show this help"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# ═══════════════════════════════════════════════════════════════════════════════
# HELPER FUNCTIONS
# ═══════════════════════════════════════════════════════════════════════════════

log_header() {
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
}

log_step() {
    echo -e "${GREEN}▶ $1${NC}"
}

log_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

log_error() {
    echo -e "${RED}✗ $1${NC}"
}

log_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

check_env() {
    if [ -z "${!1}" ]; then
        log_error "Missing environment variable: $1"
        exit 1
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# PRE-FLIGHT CHECKS
# ═══════════════════════════════════════════════════════════════════════════════

log_header "STERLING SIGNALS - FRIDAY PIPELINE"
echo "  Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo "  Mode: $([ "$TEST_MODE" = true ] && echo 'TEST' || echo 'PRODUCTION')"
echo ""

log_step "Running pre-flight checks..."

# Check required files
if [ ! -f "scanner/scanner.py" ]; then
    log_error "scanner/scanner.py not found in current directory"
    exit 1
fi

if [ ! -f "complete_tickers.txt" ]; then
    log_error "complete_tickers.txt not found"
    exit 1
fi

log_success "Pre-flight checks passed"

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1: RUN SCANNER (with DD enabled by default)
# ═══════════════════════════════════════════════════════════════════════════════

log_header "STEP 1: Running Scanner (Pure Technical Signal Detector)"

SCANNER_ARGS="--archive"

if [ "$TEST_MODE" = true ]; then
    SCANNER_ARGS="$SCANNER_ARGS --top 20"
    log_warning "Test mode: Using --top 20"
fi

log_step "python3 -m scanner.scanner $SCANNER_ARGS"
python3 -m scanner.scanner $SCANNER_ARGS

log_success "Scanner complete (signals_technical.json generated — $0 cost)"

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 1.5: GENERATE FUNNEL GRAPHIC
# ═══════════════════════════════════════════════════════════════════════════════

log_header "STEP 1.5: Generating Funnel Graphic"

if [ -f "twitter/funnel_graphic.py" ]; then
    log_step "python3 -m twitter.funnel_graphic"
    python3 -m twitter.funnel_graphic || {
        log_warning "Funnel graphic generation failed - continuing anyway"
    }
else
    log_warning "twitter/funnel_graphic.py not found, skipping"
fi

# Chart capture and batch tweet generation removed (Tweet Phase 1).
# Live tweets generated by live_tweet.yml → live_tweet_generator.py.
# Daily content handled by daily_content.yml running daily at 07:00 ET.

# ═══════════════════════════════════════════════════════════════════════════════
# STEP 2: GIT COMMIT AND PUSH
# ═══════════════════════════════════════════════════════════════════════════════

log_header "STEP 2: Git Commit and Push"

if [ "$NO_PUSH" = true ]; then
    log_warning "Skipping git push (--no-push)"
else
    log_step "Staging changes..."
    git add scanner/output/ 2>/dev/null || true
    git add portfolio/output/ 2>/dev/null || true
    git add substack/output/ 2>/dev/null || true
    git add twitter/output/ 2>/dev/null || true
    git add *.json 2>/dev/null || true

    if git diff --cached --quiet; then
        log_warning "No changes to commit"
    else
        DATE=$(date '+%Y-%m-%d')
        COMMIT_MSG="Weekly scan results $DATE"

        if [ "$TEST_MODE" = true ]; then
            COMMIT_MSG="[TEST] $COMMIT_MSG"
        fi

        log_step "Committing: $COMMIT_MSG"
        git commit -m "$COMMIT_MSG"

        log_step "Pushing to GitHub..."
        git push

        log_success "Pushed to GitHub"
    fi
fi

# ═══════════════════════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════════════════════

log_header "PIPELINE COMPLETE"

echo "  Generated files:"
echo "    • scanner/output/signals_technical.json   ← PRIMARY output"
echo "    • scanner/output/signals.json             ← Transitional (downstream compat)"
echo ""
echo "  Archived to: scanner/output/archive/$(date '+%G-W%V')/"
echo ""

if [ "$TEST_MODE" = true ]; then
    echo -e "${YELLOW}  ⚠ This was a TEST run - minimal API calls made${NC}"
else
    echo "  Pipeline completed:"
    echo "    ✅ Scanner ran (pure technical, \$0 cost)"
    echo ""
    echo "  Next steps (manual via Claude.ai chat):"
    echo "    1. Review signals_technical.json for buy/sell signals"
    echo "    2. Open Claude.ai → attach sterling_prompt_library.md"
    echo "    3. Run thematic analysis + investment gate in chat"
    echo "    4. Update portfolio with final decisions"
    echo ""
    echo "  Automated content:"
    echo "    • Live tweets via live_tweet.yml → live_tweet_generator.py"
    echo "    • Daily context + notes via daily_content.yml at 07:00 ET"
fi

echo ""
echo "  Time: $(date '+%H:%M:%S')"
echo ""
